<a href="https://colab.research.google.com/github/venkatesh176/AI_Training/blob/main/classfication_with_sklearn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report, log_loss





In [ ]:
df = pd.read_csv('/content/diabetic.txt', sep='\t')
df.count()

Age                20
BMI                20
Blood Pressure     20
Glucose Level      20
Insulin Level      20
Diabetic Status    20
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Age              20 non-null     int64  
 1   BMI              20 non-null     float64
 2   Blood Pressure   20 non-null     int64  
 3   Glucose Level    20 non-null     int64  
 4   Insulin Level    20 non-null     int64  
 5   Diabetic Status  20 non-null     object 
dtypes: float64(1), int64(4), object(1)
memory usage: 1.1+ KB


In [ ]:
df['Diabetic Status'] = np.where(df['Diabetic Status']=='Yes', 1, 0)
df['Diabetic Status']

0     1
1     1
2     0
3     1
4     1
5     0
6     0
7     1
8     0
9     1
10    0
11    1
12    0
13    1
14    0
15    1
16    0
17    1
18    0
19    1
Name: Diabetic Status, dtype: int64

In [ ]:
df.head()

Age   BMI  Blood Pressure  Glucose Level  Insulin Level  Diabetic Status
0   45  25.3             120            140             85                1
1   50  28.1             130            155             90                1
2   38  23.5             115            110             75                0
3   60  31.2             135            160             95                1
4   55  29.8             128            150             92                1

In [ ]:
X  = df.drop('Diabetic Status', axis=1) # axis=1 for column


Age   BMI  Blood Pressure  Glucose Level  Insulin Level
0    45  25.3             120            140             85
1    50  28.1             130            155             90
2    38  23.5             115            110             75
3    60  31.2             135            160             95
4    55  29.8             128            150             92
5    32  22.7             110            105             70
6    42  26.5             118            135             80
7    48  27.3             125            145             88
8    35  24.1             113            120             78
9    58  30.5             132            158             93
10   41  25.8             121            138             82
11   47  27.0             126            144             87
12   36  24.9             114            122             76
13   53  29.1             130            148             89
14   40  26.0             119            132             81
15   61  31.5             136            162             96
16   39  23.8             117            128             77
17   49  27.5             129            146             90
18   37  24.5             116            124             79
19   54  30.0             133            150             91

In [ ]:
y = df['Diabetic Status']
y


0     1
1     1
2     0
3     1
4     1
5     0
6     0
7     1
8     0
9     1
10    0
11    1
12    0
13    1
14    0
15    1
16    0
17    1
18    0
19    1
Name: Diabetic Status, dtype: int64

In [ ]:
type(y)

pandas.core.series.Series

In [ ]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [ ]:
X_train['Age'].count()

np.int64(16)

In [ ]:
X_test['Age'].count()

np.int64(4)

In [ ]:
y_train.count()

np.int64(16)

In [ ]:
y_test.count()

np.int64(4)

In [ ]:
# Initialize and fit the Logistic Regression model
model = LogisticRegression() # default 100 iteraions.
model.fit(X_train, y_train)


LogisticRegression()

In [ ]:
model.coef_

array([[0.30640372, 0.05970003, 0.24998566, 0.33954264, 0.27431778]])

In [ ]:
model.intercept_

array([-116.86048826])

In [ ]:
y_pred = model.predict(X_test)
y_pred

array([0, 1, 1, 1])

In [ ]:
y_proba = model.predict_proba(X_test)
y_proba

array([[6.70544833e-01, 3.29455167e-01],
       [1.82377682e-03, 9.98176223e-01],
       [5.33405786e-09, 9.99999995e-01],
       [4.75770021e-05, 9.99952423e-01]])

In [ ]:
y_test

0     1
17    1
15    1
1     1
Name: Diabetic Status, dtype: int64

In [ ]:
y_pred

array([0, 1, 1, 1])

In [ ]:
accuracy_score(y_test, y_pred)

0.75

In [ ]:
log_loss(y_test, y_proba)


ValueError: y_true contains only one label (1). Please provide the true labels explicitly through the labels argument.

In [ ]:
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(conf_matrix)


Confusion Matrix:
[[0 0]
 [1 3]]


In [ ]:
# all above experiments with scaling input features.
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train) # std (16), mean(16)
X_test_scaled = scaler.transform(X_test)
X_train_scaled


array([[-1.11887841, -0.96996839, -1.17419053, -0.97744815, -0.73431556],
       [-1.46536979, -1.49861297, -1.56558738, -1.91956685, -1.84010841],
       [ 0.26708711,  0.12508108,  0.52186246,  0.52994177,  0.50970139],
       [ 1.76854975,  1.71101481,  1.69605299,  1.53486838,  1.61549424],
       [-0.88788416, -0.81892709, -0.78279369, -0.7262165 , -0.59609146],
       [-0.65688991, -1.08324937, -0.65232807, -0.47498484, -0.87253967],
       [ 0.96006987,  0.91804794,  1.04372492,  0.78117342,  0.7861496 ],
       [-0.77238703, -1.19653035, -0.9132593 , -1.60552728, -1.14898788],
       [ 1.5375555 ,  1.44669252,  1.30465615,  1.40925255,  1.33904602],
       [ 1.07556699,  1.25789089,  1.43512176,  0.90678925,  1.06259781],
       [ 1.19106412,  1.18237023,  0.78279369,  0.90678925,  1.20082192],
       [-1.00338129, -0.66788578, -1.04372492, -0.85183232, -1.01076377],
       [ 0.38258423,  0.23836206,  0.39139684,  0.59274968,  0.6479255 ],
       [-0.42589565, -0.32804284, -0.1

In [ ]:
for i in range(X_train_scaled.shape[1]):
     print(X_train_scaled[:, i].std())


0.9999999999999999
0.9999999999999999
1.0
0.9999999999999999
1.0


In [ ]:
model.fit(X_train_scaled, y_train)
model.coef_


array([[0.7333962 , 0.55463831, 0.7496354 , 0.58464561, 0.7861136 ]])

In [ ]:
model.intercept_

array([-0.50395415])

In [ ]:
y_pred_scale = model.predict(X_test_scaled)
y_pred_scale

array([0, 1, 1, 1])

In [ ]:
accuracy_score(y_test, y_pred_scale)


0.75

In [ ]:
from sklearn.naive_bayes import GaussianNB

model = GaussianNB()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
accuracy_score(y_test, y_pred)

0.75

In [ ]:
from sklearn.tree import DecisionTreeClassifier

# Initialize the Decision Tree model
model = DecisionTreeClassifier()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
accuracy_score(y_test, y_pred)

0.75

In [ ]:
from sklearn.ensemble import RandomForestClassifier

# Initialize the Random Forest model
model = RandomForestClassifier(n_estimators=9)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
accuracy_score(y_test, y_pred)

1.0

In [ ]:
y_pred

array([1, 1, 1, 1])

In [ ]:
y_test

0     1
17    1
15    1
1     1
Name: Diabetic Status, dtype: int64

In [ ]:
from sklearn.svm import SVC
model = SVC()
model.fit(X_train, y_train)
y_pred= model.predict(X_test)
accuracy_score(y_test, y_pred)

0.75