<a href="https://colab.research.google.com/github/venkatesh176/Python_8AM/blob/main/graidient_with_scaling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# age , wgt, hgt are input variables.
# cholestral is target variable.
age = [25, 23, 34, 40, 20, 35, 23, 26, 30, 50]
len(age)

10

In [ ]:
wgt = [50, 48, 70, 79, 45, 71, 48, 55, 59, 98]
hgt = [5.1, 5.2, 5.6, 5.9, 5.3, 6.0, 5.9, 5.5, 5.4, 5.9]


In [ ]:
import numpy as np
age = np.array(age)
wgt = np.array(wgt)
hgt = np.array(hgt)
chol = 5 + 2 * age + 3* wgt - 1.5 * hgt
chol


array([197.35, 187.2 , 274.6 , 313.15, 172.05, 279.  , 186.15, 213.75,
       233.9 , 390.15])

In [ ]:
# step1 : feature matrix.
ones = np.ones(len(age))
X = np.c_[ones, age, wgt, hgt]
X.shape

(10, 4)

In [ ]:
X

array([[ 1. , 25. , 50. ,  5.1],
       [ 1. , 23. , 48. ,  5.2],
       [ 1. , 34. , 70. ,  5.6],
       [ 1. , 40. , 79. ,  5.9],
       [ 1. , 20. , 45. ,  5.3],
       [ 1. , 35. , 71. ,  6. ],
       [ 1. , 23. , 48. ,  5.9],
       [ 1. , 26. , 55. ,  5.5],
       [ 1. , 30. , 59. ,  5.4],
       [ 1. , 50. , 98. ,  5.9]])

In [ ]:
# step2 : label matrix
Y = np.c_[chol]
Y.shape

(10, 1)

In [ ]:
Y

array([[197.35],
       [187.2 ],
       [274.6 ],
       [313.15],
       [172.05],
       [279.  ],
       [186.15],
       [213.75],
       [233.9 ],
       [390.15]])

In [ ]:
# Random weights.
np.random.seed(101)
W = np.random.random((X.shape[1], Y.shape[1])) *2 - 1
W.shape

(4, 1)

In [ ]:
W

array([[ 0.03279726],
       [ 0.14133517],
       [-0.94305155],
       [-0.65695669]])

In [ ]:
def predict(x, w):
   return x.dot(w)

def mse(y, ycap):
   return ((y-ycap)**2).mean()

def derivative(x, y, ycap):
    return   x.T.dot(y-ycap)/y.size

def rsquare(y, ycap):
   rss = ((y-ycap)**2).sum()
   tss = ((y-y.mean())**2).sum()
   return 1 - (rss/tss)


In [ ]:
# train model
convergence = 0.0000000001
pe=0
flag=0
alpha = 0.002
for i in range(5):
   ycap = predict(X, W)
   ce = mse(Y, ycap)
   print(ce)
   '''
   if i%1000==0:
     print("Current Error after ", i+1 , " iterations ", ce)
   '''
   delta = derivative(X, Y, ycap)
   W += delta * alpha
   if np.abs(pe-ce) <= convergence:
      print(" Training Completed after ", i+1 , " iterations ")
      flag=1
      break
   pe=ce
if flag==0:
  print(" Training not completed , run more iterations ")


512823708675016.2
4.504638473848561e+16
3.9568700582320154e+18
3.475710814225796e+20
3.053061001837375e+22
 Training not completed , run more iterations 


In [ ]:
# in above trials of 5 iterations.
# loss keep on increasing .
# its the indication, the data needs scaling.

In [ ]:
for c in range(X.shape[1]):
   if c!=0:
      print(X[:,c].std())

#  variance of each input variable  is different



8.811356308764276
16.161992451427516
0.3124099870362663


In [ ]:
# scaling.
def scale(x):
   return (x-x.mean())/x.std()




In [ ]:
X_scale = np.copy(X)
for c in range(X_scale.shape[1]):
  if c!=0:
      X_scale[:, c] = scale(X_scale[:, c])
X_scale

array([[ 1.        , -0.63554347, -0.76104478, -1.53644256],
       [ 1.        , -0.86252329, -0.8847919 , -1.21635036],
       [ 1.        ,  0.38586568,  0.47642641,  0.06401844],
       [ 1.        ,  1.06680512,  1.03328844,  1.02429504],
       [ 1.        , -1.202993  , -1.07041258, -0.89625816],
       [ 1.        ,  0.49935559,  0.53829997,  1.34438724],
       [ 1.        , -0.86252329, -0.8847919 ,  1.02429504],
       [ 1.        , -0.52205357, -0.45167698, -0.25607376],
       [ 1.        , -0.06809394, -0.20418275, -0.57616596],
       [ 1.        ,  2.20170418,  2.20888607,  1.02429504]])

In [ ]:
for c in range(X_scale.shape[1]):
   if c!=0:
     print(X_scale[:,c].std())

1.0
1.0
1.0


In [ ]:
# after scaling ,
# each variable's  stadard deviation is close to 1 or equal to 1.
# sd ~=1


In [ ]:
Y_scale = np.copy(Y)
Y_scale = scale(Y_scale)
Y_scale[:,0].std()

1.0

In [ ]:
X

array([[ 1. , 25. , 50. ,  5.1],
       [ 1. , 23. , 48. ,  5.2],
       [ 1. , 34. , 70. ,  5.6],
       [ 1. , 40. , 79. ,  5.9],
       [ 1. , 20. , 45. ,  5.3],
       [ 1. , 35. , 71. ,  6. ],
       [ 1. , 23. , 48. ,  5.9],
       [ 1. , 26. , 55. ,  5.5],
       [ 1. , 30. , 59. ,  5.4],
       [ 1. , 50. , 98. ,  5.9]])

In [ ]:
X_scale

array([[ 1.        , -0.63554347, -0.76104478, -1.53644256],
       [ 1.        , -0.86252329, -0.8847919 , -1.21635036],
       [ 1.        ,  0.38586568,  0.47642641,  0.06401844],
       [ 1.        ,  1.06680512,  1.03328844,  1.02429504],
       [ 1.        , -1.202993  , -1.07041258, -0.89625816],
       [ 1.        ,  0.49935559,  0.53829997,  1.34438724],
       [ 1.        , -0.86252329, -0.8847919 ,  1.02429504],
       [ 1.        , -0.52205357, -0.45167698, -0.25607376],
       [ 1.        , -0.06809394, -0.20418275, -0.57616596],
       [ 1.        ,  2.20170418,  2.20888607,  1.02429504]])

In [ ]:
Y

array([[197.35],
       [187.2 ],
       [274.6 ],
       [313.15],
       [172.05],
       [279.  ],
       [186.15],
       [213.75],
       [233.9 ],
       [390.15]])

In [ ]:
Y_scale

array([[-0.72052578],
       [-0.87488071],
       [ 0.45424451],
       [ 1.0404891 ],
       [-1.10527255],
       [ 0.52115699],
       [-0.89084846],
       [-0.47112471],
       [-0.16469595],
       [ 2.21145754]])

In [ ]:
np.random.seed(101)
W = np.random.random((X.shape[1], Y.shape[1])) * 2-1
W.shape

(4, 1)

In [ ]:
W

array([[ 0.03279726],
       [ 0.14133517],
       [-0.94305155],
       [-0.65695669]])

In [ ]:
# train model
convergence = 0.0000000001
pe=0
flag=0
alpha = 0.002
for i in range(1000000):
   ycap = predict(X_scale, W)
   ce = mse(Y_scale, ycap)
   if i%1000==0:
     print("Current Error after ", i+1 , " iterations ", ce)
   delta = derivative(X_scale, Y_scale, ycap)
   W += delta * alpha
   if np.abs(pe-ce) <= convergence:
      print(" Training Completed after ", i+1 , " iterations ")
      flag=1
      break
   pe=ce
if flag==0:
  print(" Training not completed , run more iterations ")


Current Error after  1  iterations  0.0003004877312402257
Current Error after  1001  iterations  0.00029668822539332393
Current Error after  2001  iterations  0.0002929367622555905
Current Error after  3001  iterations  0.0002892327343527908
Current Error after  4001  iterations  0.00028557554189188
Current Error after  5001  iterations  0.0002819645926638615
Current Error after  6001  iterations  0.00027839930194792015
Current Error after  7001  iterations  0.00027487909241670836
Current Error after  8001  iterations  0.00027140339404287513
Current Error after  9001  iterations  0.0002679716440067637
Current Error after  10001  iterations  0.0002645832866052638
Current Error after  11001  iterations  0.000261237773161835
Current Error after  12001  iterations  0.00025793456193766364
Current Error after  13001  iterations  0.00025467311804391255
Current Error after  14001  iterations  0.0002514529133551451
Current Error after  15001  iterations  0.00024827342642378444
Current Error aft

In [ ]:
W

array([[-3.88581437e-16],
       [ 3.02787154e-01],
       [ 7.01867939e-01],
       [-6.07955720e-03]])

In [ ]:
ycap = predict(X_scale, W)
ycap

array([[-0.71724644],
       [-0.87477317],
       [ 0.45083439],
       [ 1.04201965],
       [-1.11009025],
       [ 0.52084067],
       [-0.8883953 ],
       [-0.47353189],
       [-0.16042446],
       [ 2.2107668 ]])

In [ ]:
rsquare(Y_scale, ycap)

0.9999921417307455

In [ ]:
# unscale.
def unscale(scaled, original):
   return scaled*original.std() + original.mean()


In [ ]:
ycap_unscaled = unscale(ycap, Y)
ycap_unscaled


array([[197.56564101],
       [187.20707162],
       [274.37575872],
       [313.2506454 ],
       [171.73320023],
       [278.97919909],
       [186.31131378],
       [213.59170931],
       [234.18088268],
       [390.10457817]])

In [ ]:
np.c_[Y, ycap_unscaled]

array([[197.35      , 197.56564101],
       [187.2       , 187.20707162],
       [274.6       , 274.37575872],
       [313.15      , 313.2506454 ],
       [172.05      , 171.73320023],
       [279.        , 278.97919909],
       [186.15      , 186.31131378],
       [213.75      , 213.59170931],
       [233.9       , 234.18088268],
       [390.15      , 390.10457817]])

In [ ]:

new_age = [35, 30, 25, 20, 34]
new_wgt = [69, 61, 48, 42, 70]
new_hgt = [6.0, 5.6, 5.4, 5.8, 5.5]
a = np.array(new_age)
wt = np.array(new_wgt)
h = np.array(new_hgt)

ascale = scale(a)
wtscale= scale(wt)
hscale = scale(h)
one = np.ones(len(a))
P = np.c_[one, ascale, wtscale, hscale]
P

array([[ 1.        ,  1.10014883,  0.97995789,  1.57841037],
       [ 1.        ,  0.21293203,  0.26726124, -0.27854301],
       [ 1.        , -0.67428477, -0.89087081, -1.2070197 ],
       [ 1.        , -1.56150157, -1.42539329,  0.64993368],
       [ 1.        ,  0.92270547,  1.06904497, -0.74278135]])

In [ ]:
new_ycap = predict(P, W)
new_ycap

array([[ 1.01131592],
       [ 0.2537486 ],
       [-0.82210028],
       [-1.47719178],
       [ 1.03422753]])

In [ ]:
cholestrals_new = unscale(new_ycap, Y)
cholestrals_new

array([[311.23164352],
       [261.41588277],
       [190.67071102],
       [147.59350792],
       [312.73825478]])

In [ ]:
Y

array([[197.35],
       [187.2 ],
       [274.6 ],
       [313.15],
       [172.05],
       [279.  ],
       [186.15],
       [213.75],
       [233.9 ],
       [390.15]])



```
Learning Summary:
 1. Task: based on age,weight, height predict cholestral level.
 2. train model with out scaling.
 3. what to do if Loss increased.
 4. Scaling features and labels.
 5. what happens after scaling.
 6. create scale function
 7. apply scale function on feature and label matrix.
 8. train model with scaled features and labels.
 9. quality check of trained model.
 10. apply predictions.
 11. how to unscale scaled predictions.

```

