<a href="https://colab.research.google.com/github/venkatesh176/AI_Training/blob/main/LinearRegression_Gradient.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import numpy as np
import pandas as pd

In [27]:
df = pd.read_csv("/content/sample_data/income.txt", sep ="\t")
df.head()
y = df["income"]
X = df.drop("income" , axis =1)
y = np.array(y)
X = np.array(X)
ones = np.ones(len(X))
X = np.c_[ones, X]
y = np.c_[y]
X,y

(array([[ 1., 58.,  4.],
        [ 1., 48., 18.],
        [ 1., 34.,  8.],
        [ 1., 27.,  4.],
        [ 1., 40.,  2.],
        [ 1., 50.,  3.],
        [ 1., 40., 14.],
        [ 1., 32.,  7.],
        [ 1., 20.,  3.],
        [ 1., 35.,  1.],
        [ 1., 48., 14.],
        [ 1., 50., 20.],
        [ 1., 34., 10.],
        [ 1., 29.,  6.],
        [ 1., 42.,  4.],
        [ 1., 55.,  5.],
        [ 1., 45., 12.],
        [ 1., 32., 10.],
        [ 1., 30.,  5.],
        [ 1., 45.,  7.]]),
 array([[136.18],
        [150.47],
        [ 99.38],
        [ 77.52],
        [ 92.06],
        [126.18],
        [140.47],
        [ 90.38],
        [ 67.52],
        [ 82.06],
        [166.18],
        [160.47],
        [129.38],
        [ 97.52],
        [102.06],
        [136.18],
        [130.47],
        [100.38],
        [ 97.52],
        [112.06]]))

In [31]:
X.shape, y.shape

((20, 3), (20, 1))

In [58]:
def scale(x):
  return (x-x.mean())/x.std()

def scaledMatrix(x):
  for i in range(x.shape[1]):
    if i!=0:
      x[:,i]= scale(x[:,i])
  return x

def unScale(orig,scal):
  return scal*orig.std()+orig.mean()

X_act = np.copy(X)
y_act = np.copy(y)
X_scale = scaledMatrix(X)
y_scale = scale(y)
X_scale,y_scale

(array([[ 1.        ,  1.85607541, -0.7364797 ],
        [ 1.        ,  0.84182655,  1.94162829],
        [ 1.        , -0.57812185,  0.02869401],
        [ 1.        , -1.28809605, -0.7364797 ],
        [ 1.        ,  0.03042747, -1.11906655],
        [ 1.        ,  1.04467633, -0.92777312],
        [ 1.        ,  0.03042747,  1.17645458],
        [ 1.        , -0.78097162, -0.16259941],
        [ 1.        , -1.99807026, -0.92777312],
        [ 1.        , -0.47669696, -1.31035998],
        [ 1.        ,  0.84182655,  1.17645458],
        [ 1.        ,  1.04467633,  2.32421514],
        [ 1.        , -0.57812185,  0.41128087],
        [ 1.        , -1.08524628, -0.35389284],
        [ 1.        ,  0.23327724, -0.7364797 ],
        [ 1.        ,  1.55180076, -0.54518627],
        [ 1.        ,  0.5375519 ,  0.79386772],
        [ 1.        , -0.78097162,  0.41128087],
        [ 1.        , -0.98382139, -0.54518627],
        [ 1.        ,  0.5375519 , -0.16259941]]),
 array([[ 0.778826

In [59]:
print(y_scale.std())
for i in range(X_scale.shape[1]):
  if i!=0:
    print(X_scale[:,i].std())




1.0
1.0
1.0


In [60]:
def pred(x,w):
  return x.dot(w)

def mse (y,ycap):
  return ((y-ycap)**2).mean()

def der(x,y,ycap):
  return x.T.dot(y-ycap)/y.size

In [61]:
np.random.seed(42)
w= np.random.random((X_scale.shape[1],y_scale.shape[1]))*2-1
w

array([[-0.25091976],
       [ 0.90142861],
       [ 0.46398788]])

In [72]:
conv = 0.00000000001
flag = 0
pe = 0
alpha = 0.002

for i in range(1000000):
  ycap = pred(X_scale,w)
  ce = mse(y_scale, ycap)
  delta = der(X_scale,y_scale,ycap)
  w+= delta*alpha
  if i%1000 == 0:
    print(f"Training is not complete error {ce} at {i+1}")
  if np.abs(ce-pe)<= conv:
    flag = 1
    print(f"Training is complete at {i+1}")
    break
  pe=ce

if flag!=1:
  print("Training is not complete")



Training is not complete error 0.0948536707695698 at 1
Training is not complete error 0.09485037737763743 at 1001
Training is not complete error 0.09485018313509627 at 2001
Training is complete at 2444


In [73]:
ycap = pred(X_scale,w)

def r2_score(y,ycap):
  rss = ((y-ycap)**2).sum()
  tss = ((y-y.mean())**2).sum()
  return 1-rss/tss

ycap_unscale = unScale(y_act,ycap)

r2 = r2_score(y_scale,ycap)
print(r2)

0.9051498256601


In [74]:
ycap_unscale
np.c_[y,ycap_unscale]

array([[136.18      , 135.26630563],
       [150.47      , 158.99469945],
       [ 99.38      , 105.24004622],
       [ 77.52      ,  81.30104409],
       [ 92.06      ,  98.05498868],
       [126.18      , 118.40146204],
       [140.47      , 133.31488243],
       [ 90.38      ,  98.82009197],
       [ 67.52      ,  66.17701539],
       [ 82.06      ,  86.41258976],
       [166.18      , 147.24140153],
       [160.47      , 168.35297818],
       [129.38      , 111.11669518],
       [ 97.52      ,  90.65932282],
       [102.06      , 107.41326742],
       [136.18      , 132.98218544],
       [130.47      , 136.14230791],
       [100.38      , 107.6350654 ],
       [ 97.52      ,  89.46181323],
       [112.06      , 121.45068552]])