<a href="https://colab.research.google.com/github/venkatesh176/AI_Training/blob/main/Logistic_Sklearn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [51]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler, PolynomialFeatures, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix,classification_report
from sklearn.pipeline import Pipeline, make_pipeline
from sklearn.linear_model import LogisticRegression

In [2]:
df = pd.read_csv("/content/sample_data/PatientData.txt", sep="\t")
df.head()

Age   BMI  Blood Pressure  Glucose Level  Insulin Level Diabetic Status
0   45  25.3             120            140             85             Yes
1   50  28.1             130            155             90             Yes
2   38  23.5             115            110             75              No
3   60  31.2             135            160             95             Yes
4   55  29.8             128            150             92             Yes

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Age              20 non-null     int64  
 1   BMI              20 non-null     float64
 2   Blood Pressure   20 non-null     int64  
 3   Glucose Level    20 non-null     int64  
 4   Insulin Level    20 non-null     int64  
 5   Diabetic Status  20 non-null     object 
dtypes: float64(1), int64(4), object(1)
memory usage: 1.1+ KB


In [14]:
op = df["Diabetic Status"]
op1 = np.array(op)
y = np.c_[op]
# y = np.where(y== 'Yes',1,0)
le = LabelEncoder()
df['Diabetic Status_encoded'] = le.fit_transform(df["Diabetic Status"])
y = df['Diabetic Status_encoded']
y = np.array(y)
y = np.c_[y]
y
# df['Diabetic Status_decoded'] = le.inverse_transform(df['Diabetic Status_encoded'])


array([[1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1]])

In [39]:
x = df.drop(["Diabetic Status",'Diabetic Status_encoded','Diabetic Status_decoded'], axis=1)
x = np.array(x)
ones = np.ones(len(x))
x = np.c_[ones,x]
x

array([[  1. ,  45. ,  25.3, 120. , 140. ,  85. ],
       [  1. ,  50. ,  28.1, 130. , 155. ,  90. ],
       [  1. ,  38. ,  23.5, 115. , 110. ,  75. ],
       [  1. ,  60. ,  31.2, 135. , 160. ,  95. ],
       [  1. ,  55. ,  29.8, 128. , 150. ,  92. ],
       [  1. ,  32. ,  22.7, 110. , 105. ,  70. ],
       [  1. ,  42. ,  26.5, 118. , 135. ,  80. ],
       [  1. ,  48. ,  27.3, 125. , 145. ,  88. ],
       [  1. ,  35. ,  24.1, 113. , 120. ,  78. ],
       [  1. ,  58. ,  30.5, 132. , 158. ,  93. ],
       [  1. ,  41. ,  25.8, 121. , 138. ,  82. ],
       [  1. ,  47. ,  27. , 126. , 144. ,  87. ],
       [  1. ,  36. ,  24.9, 114. , 122. ,  76. ],
       [  1. ,  53. ,  29.1, 130. , 148. ,  89. ],
       [  1. ,  40. ,  26. , 119. , 132. ,  81. ],
       [  1. ,  61. ,  31.5, 136. , 162. ,  96. ],
       [  1. ,  39. ,  23.8, 117. , 128. ,  77. ],
       [  1. ,  49. ,  27.5, 129. , 146. ,  90. ],
       [  1. ,  37. ,  24.5, 116. , 124. ,  79. ],
       [  1. ,  54. ,  30. , 13

In [40]:
ss = StandardScaler()
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)
print(x_train.shape,y_train.shape,x_test.shape,y_test.shape)

(16, 6) (16, 1) (4, 6) (4, 1)


In [41]:
x_train_scale = ss.fit_transform(x_train)
x_test_scale = ss.transform(x_test)



In [46]:
model = LogisticRegression()
model.fit(x_train_scale,y_train.ravel())
ycap = model.predict(x_test_scale)
ycap

# print(x_train_scale.shape,y_train.shape,x_test_scale.shape)

array([0, 1, 1, 1])

In [47]:
cm = confusion_matrix(y_test, ycap)
cm

array([[0, 0],
       [1, 3]])

In [48]:
ac = accuracy_score(y_test, ycap)
ac

0.75

In [54]:
classification_report(y_test, ycap, zero_division=0)


'              precision    recall  f1-score   support\n\n           0       0.00      0.00      0.00         0\n           1       1.00      0.75      0.86         4\n\n    accuracy                           0.75         4\n   macro avg       0.50      0.38      0.43         4\nweighted avg       1.00      0.75      0.86         4\n'