<a href="https://colab.research.google.com/github/venkatesh176/AI_Training/blob/main/loss_functions_crossentropy_and_mse.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
y = [1, 1, 0, 0, 1, 1, 0, 1]
len(y)

8

In [ ]:
# predicted probabilities.
ycap = [0.9, 0.8, 0.1, 0.05, 0.95, 0.91, 0.2, 0.87]
len(ycap)

8

In [ ]:
import numpy as np
y = np.array(y)
ycap = np.array(ycap)


In [ ]:
ce_left =  y * np.log(ycap)
ce_left

array([-0.10536052, -0.22314355, -0.        , -0.        , -0.05129329,
       -0.09431068, -0.        , -0.13926207])

In [ ]:
ce_right = (1-y) * np.log(1-ycap)
ce_right

array([-0.        , -0.        , -0.10536052, -0.05129329, -0.        ,
       -0.        , -0.22314355, -0.        ])

In [ ]:
ce_add = ce_left + ce_right
ce_add

array([-0.10536052, -0.22314355, -0.10536052, -0.05129329, -0.05129329,
       -0.09431068, -0.22314355, -0.13926207])

In [ ]:
n = y.size
ce = -(np.sum(ce_add))/n
ce

np.float64(0.12414593369049026)

In [ ]:
def cross_entropy(y, ycap):
   ce_left= y * np.log(ycap)
   ce_right= (1-y) * np.log(1-ycap)
   ce_add= ce_left + ce_right
   n = y.size
   ce =  -(np.sum(ce_add))/n
   return ce


In [ ]:
cross_entropy(y, ycap)


np.float64(0.12414593369049026)

In [ ]:
# 2nd way --> using sklearn .
from sklearn.metrics import  log_loss


In [ ]:
log_loss(y, ycap)

0.12414593369049026

In [ ]:

def accuracy(y, ycap):
  ylabels = np.where(ycap>0.5, 1, 0)
  pcnt = np.where(y==ylabels)[0].size
  acc = pcnt/y.size * 100
  return acc
accuracy(y, ycap)

100.0

In [ ]:
# 2nd way of accuracy . using sklearn.
from sklearn.metrics import accuracy_score
ylabels = np.where(ycap>0.5, 1, 0)
accuracy_score(y, ylabels)

1.0

In [ ]:
# loss funciton for regression.
y = [10, 20, 30, 50, 80, 25, 35]
ycap = [9, 20.7, 29, 51, 79.99, 24, 35.3]
y = np.array(y)
ycap = np.array(ycap)
def mse(y, ycap):
   e = y- ycap
   e2 = e**2
   return e2.mean()


In [ ]:
mse(y, ycap)

np.float64(0.6542999999999995)

In [ ]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y, ycap)


0.6542999999999995

In [ ]:
from sklearn.metrics import r2_score
r2_score(y, ycap)    # 1-(rss/tss)
# rss --> ((y-ycap)**2).sum()
# tss --> ((y-y.mean())**2).sum()


0.9985782394678492

In [ ]:
def rsquared(y, ycap):
   rss = ((y-ycap)**2).sum()
   tss = ((y-y.mean())**2).sum()
   return 1 - (rss/tss)


In [ ]:
rsquared(y, ycap)

np.float64(0.9985782394678492)