<a href="https://colab.research.google.com/github/venkatesh176/AI_Training/blob/Basics/LR_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import confusion_matrix, accuracy_score, mean_squared_error
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [4]:
df = pd.read_csv("/content/sample_data/income_1.txt", sep="\t")


In [5]:
df.head()

age  experience  income
0   58           4  136.18
1   48          18  150.47
2   34           8   99.38
3   27           4   77.52
4   40           2   92.06

In [6]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   age         20 non-null     int64  
 1   experience  20 non-null     int64  
 2   income      20 non-null     float64
dtypes: float64(1), int64(2)
memory usage: 612.0 bytes


age  experience      income
count  20.000000   20.000000   20.000000
mean   39.700000    7.850000  114.722000
std    10.115647    5.363375   28.267464
min    20.000000    1.000000   67.520000
25%    32.000000    4.000000   96.155000
50%    40.000000    6.500000  107.060000
75%    48.000000   10.500000  136.180000
max    58.000000   20.000000  166.180000

In [7]:
op = df['income']
ip = df.drop('income', axis =1)

In [8]:
ip

age  experience
0    58           4
1    48          18
2    34           8
3    27           4
4    40           2
5    50           3
6    40          14
7    32           7
8    20           3
9    35           1
10   48          14
11   50          20
12   34          10
13   29           6
14   42           4
15   55           5
16   45          12
17   32          10
18   30           5
19   45           7

In [9]:
op

0     136.18
1     150.47
2      99.38
3      77.52
4      92.06
5     126.18
6     140.47
7      90.38
8      67.52
9      82.06
10    166.18
11    160.47
12    129.38
13     97.52
14    102.06
15    136.18
16    130.47
17    100.38
18     97.52
19    112.06
Name: income, dtype: float64

In [10]:
x = np.array(ip)
y = np.array(op)


In [11]:
ones = np.ones(len(x))
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [12]:
X = np.c_[ones,x]
X

array([[ 1., 58.,  4.],
       [ 1., 48., 18.],
       [ 1., 34.,  8.],
       [ 1., 27.,  4.],
       [ 1., 40.,  2.],
       [ 1., 50.,  3.],
       [ 1., 40., 14.],
       [ 1., 32.,  7.],
       [ 1., 20.,  3.],
       [ 1., 35.,  1.],
       [ 1., 48., 14.],
       [ 1., 50., 20.],
       [ 1., 34., 10.],
       [ 1., 29.,  6.],
       [ 1., 42.,  4.],
       [ 1., 55.,  5.],
       [ 1., 45., 12.],
       [ 1., 32., 10.],
       [ 1., 30.,  5.],
       [ 1., 45.,  7.]])

In [13]:
y = np.c_[y]
y

array([[136.18],
       [150.47],
       [ 99.38],
       [ 77.52],
       [ 92.06],
       [126.18],
       [140.47],
       [ 90.38],
       [ 67.52],
       [ 82.06],
       [166.18],
       [160.47],
       [129.38],
       [ 97.52],
       [102.06],
       [136.18],
       [130.47],
       [100.38],
       [ 97.52],
       [112.06]])

In [14]:
np.random.seed(42)


In [15]:
w = np.random.rand(X.shape[1], y.shape[1])*2-1
w.shape
w


array([[-0.25091976],
       [ 0.90142861],
       [ 0.46398788]])

In [16]:
def pred(x, w):
  return x.dot(w)


In [17]:
def error(y,ycap):
  return ((y-ycap)**2).mean()

In [18]:
def der(x,y,ycap):
  return x.T.dot(y-ycap)/y.size

In [19]:
def scale(x):
  return (x-x.mean())/x.std()

In [20]:
def scaleMatrix(x):
  for i in range(x.shape[1]):
     if i!=0:
        x[:,i] = scale(x[:,i])
  return x



In [21]:
X_act = np.copy(X)
y_act = np.copy(y)
x_scale  = scaleMatrix(X)
y_scale = scale(y)

In [22]:
for i in range(x_scale.shape[1]):
  if i!=0:
    print(scale(x_scale[:,i]).std())


1.0
1.0


In [23]:
print(y_scale.std())

1.0


In [24]:
conv = 0.00000000000001
alpha = 0.002
pe = 0
flag=False

for i in range(1000000000):
  ycap = pred(x_scale,w)
  e =  y_scale-ycap
  ce = error(y_scale,ycap)
  delta = der(x_scale,y_scale,ycap)
  w += delta* alpha
  if i%1000 == 0:
    print(f"iteration not complete {i+1} and ce {ce}")
  if np.abs(ce-pe) <= conv:
    print(f"iteration completed {i+1} and ce {ce}")
    flag = True
    break
  pe=ce





iteration not complete 1 and ce 0.22866202483263307
iteration not complete 1001 and ce 0.09903963328507608
iteration not complete 2001 and ce 0.09504674068121295
iteration not complete 3001 and ce 0.09486104469900465
iteration not complete 4001 and ce 0.09485080658386336
iteration not complete 5001 and ce 0.09485020863457419
iteration not complete 6001 and ce 0.09485017307236648
iteration not complete 7001 and ce 0.09485017094551934
iteration not complete 8001 and ce 0.09485017081810344
iteration completed 8295 and ce 0.09485017081353098


In [25]:
w

array([[-1.53948284e-08],
       [ 6.22910413e-01],
       [ 5.57556395e-01]])

In [26]:
ycap = pred(x_scale,w)
ycap

array([[ 0.74553972],
       [ 1.60694978],
       [-0.3441196 ],
       [-1.21299742],
       [-0.60498914],
       [ 0.13345391],
       [ 0.67489334],
       [-0.57713371],
       [-1.76190462],
       [-1.0275391 ],
       [ 1.18032228],
       [ 1.94662076],
       [-0.13080586],
       [-0.87332644],
       [-0.26531816],
       [ 0.66266074],
       [ 0.77747268],
       [-0.25716309],
       [-0.9168047 ],
       [ 0.24418832]])

In [27]:
def unscale(x_scale, x_orig):
  return x_scale * x_orig.std()+ x_orig.mean()

In [28]:
ycap_unscale = unscale(ycap, y_act)

In [29]:
ycap_unscale

array([[135.26289873],
       [158.99622398],
       [105.24091437],
       [ 81.30183947],
       [ 98.05351098],
       [118.39888419],
       [133.31646974],
       [ 98.82097581],
       [ 66.17850425],
       [ 86.41153442],
       [147.24190439],
       [168.35474244],
       [111.11807417],
       [ 90.66035792],
       [107.41202943],
       [132.97944064],
       [136.1427066 ],
       [107.6367155 ],
       [ 89.46245736],
       [121.44980712]])

In [30]:
print(np.c_[y, ycap_unscale])

[[136.18       135.26289873]
 [150.47       158.99622398]
 [ 99.38       105.24091437]
 [ 77.52        81.30183947]
 [ 92.06        98.05351098]
 [126.18       118.39888419]
 [140.47       133.31646974]
 [ 90.38        98.82097581]
 [ 67.52        66.17850425]
 [ 82.06        86.41153442]
 [166.18       147.24190439]
 [160.47       168.35474244]
 [129.38       111.11807417]
 [ 97.52        90.66035792]
 [102.06       107.41202943]
 [136.18       132.97944064]
 [130.47       136.1427066 ]
 [100.38       107.6367155 ]
 [ 97.52        89.46245736]
 [112.06       121.44980712]]


In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   age         20 non-null     int64  
 1   experience  20 non-null     int64  
 2   income      20 non-null     float64
dtypes: float64(1), int64(2)
memory usage: 612.0 bytes


In [32]:
X

array([[ 1.        ,  1.85607541, -0.7364797 ],
       [ 1.        ,  0.84182655,  1.94162829],
       [ 1.        , -0.57812185,  0.02869401],
       [ 1.        , -1.28809605, -0.7364797 ],
       [ 1.        ,  0.03042747, -1.11906655],
       [ 1.        ,  1.04467633, -0.92777312],
       [ 1.        ,  0.03042747,  1.17645458],
       [ 1.        , -0.78097162, -0.16259941],
       [ 1.        , -1.99807026, -0.92777312],
       [ 1.        , -0.47669696, -1.31035998],
       [ 1.        ,  0.84182655,  1.17645458],
       [ 1.        ,  1.04467633,  2.32421514],
       [ 1.        , -0.57812185,  0.41128087],
       [ 1.        , -1.08524628, -0.35389284],
       [ 1.        ,  0.23327724, -0.7364797 ],
       [ 1.        ,  1.55180076, -0.54518627],
       [ 1.        ,  0.5375519 ,  0.79386772],
       [ 1.        , -0.78097162,  0.41128087],
       [ 1.        , -0.98382139, -0.54518627],
       [ 1.        ,  0.5375519 , -0.16259941]])

In [33]:
y

array([[136.18],
       [150.47],
       [ 99.38],
       [ 77.52],
       [ 92.06],
       [126.18],
       [140.47],
       [ 90.38],
       [ 67.52],
       [ 82.06],
       [166.18],
       [160.47],
       [129.38],
       [ 97.52],
       [102.06],
       [136.18],
       [130.47],
       [100.38],
       [ 97.52],
       [112.06]])

In [34]:
df = pd.read_csv("/content/sample_data/income_1.txt", sep ='\t')
y = df["income"]
X = df.drop("income", axis=1)



In [35]:
y

0     136.18
1     150.47
2      99.38
3      77.52
4      92.06
5     126.18
6     140.47
7      90.38
8      67.52
9      82.06
10    166.18
11    160.47
12    129.38
13     97.52
14    102.06
15    136.18
16    130.47
17    100.38
18     97.52
19    112.06
Name: income, dtype: float64

In [36]:
x_train,x_test,y_train, y_test = train_test_split(X,y,test_size= 0.2, random_state=42)

In [37]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train_scale = sc.fit_transform(x_train)
x_test_scale = sc.transform(x_test)

In [38]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x_train_scale, y_train)



LinearRegression()

In [39]:
ycap = model.predict(x_test_scale)

In [40]:
from sklearn.metrics import r2_score


In [41]:
r2s = r2_score(y_test,ycap)

In [42]:
r2s

0.7854874380360295