<a href="https://colab.research.google.com/github/venkatesh176/AI_Training/blob/main/ML_logistic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# statistical approach to build Logistic regression.



```

input file : diabetic.txt

Age	BMI	Blood Pressure	Glucose Level	Insulin Level	Diabetic Status
45	25.3	120	140	85	Yes
50	28.1	130	155	90	Yes
38	23.5	115	110	75	No
60	31.2	135	160	95	Yes
55	29.8	128	150	92	Yes
32	22.7	110	105	70	No
42	26.5	118	135	80	No
48	27.3	125	145	88	Yes
35	24.1	113	120	78	No
58	30.5	132	158	93	Yes
41	25.8	121	138	82	No
47	27.0	126	144	87	Yes
36	24.9	114	122	76	No
53	29.1	130	148	89	Yes
40	26.0	119	132	81	No
61	31.5	136	162	96	Yes
39	23.8	117	128	77	No
49	27.5	129	146	90	Yes
37	24.5	116	124	79	No
54	30.0	133	150	91	Yes
```



In [ ]:
infile = open('/content/diabetic.txt')
head = infile.readline()
head

'Age\tBMI\tBlood Pressure\tGlucose Level\tInsulin Level\tDiabetic Status\n'

In [ ]:
data = infile.readlines()
len(data)

20

In [ ]:
inputs = []
target = []
for line in data:
   w = line.strip().lower().split('\t')
   ins = [float(v) for v in w[:-1]]
   inputs.append(ins)
   t = w[-1]
   if t=='yes':
      target.append(1)
   else:
      target.append(0)


In [ ]:
inputs

[[45.0, 25.3, 120.0, 140.0, 85.0],
 [50.0, 28.1, 130.0, 155.0, 90.0],
 [38.0, 23.5, 115.0, 110.0, 75.0],
 [60.0, 31.2, 135.0, 160.0, 95.0],
 [55.0, 29.8, 128.0, 150.0, 92.0],
 [32.0, 22.7, 110.0, 105.0, 70.0],
 [42.0, 26.5, 118.0, 135.0, 80.0],
 [48.0, 27.3, 125.0, 145.0, 88.0],
 [35.0, 24.1, 113.0, 120.0, 78.0],
 [58.0, 30.5, 132.0, 158.0, 93.0],
 [41.0, 25.8, 121.0, 138.0, 82.0],
 [47.0, 27.0, 126.0, 144.0, 87.0],
 [36.0, 24.9, 114.0, 122.0, 76.0],
 [53.0, 29.1, 130.0, 148.0, 89.0],
 [40.0, 26.0, 119.0, 132.0, 81.0],
 [61.0, 31.5, 136.0, 162.0, 96.0],
 [39.0, 23.8, 117.0, 128.0, 77.0],
 [49.0, 27.5, 129.0, 146.0, 90.0],
 [37.0, 24.5, 116.0, 124.0, 79.0],
 [54.0, 30.0, 133.0, 150.0, 91.0]]

In [ ]:
target

[1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1]

In [ ]:
import numpy as np

In [ ]:
ones = np.ones(len(data))
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [ ]:
X = np.c_[ones,inputs]
X.shape

(20, 6)

In [ ]:
Y = np.c_[target]

In [ ]:
Y.shape

(20, 1)

In [ ]:
X

array([[  1. ,  45. ,  25.3, 120. , 140. ,  85. ],
       [  1. ,  50. ,  28.1, 130. , 155. ,  90. ],
       [  1. ,  38. ,  23.5, 115. , 110. ,  75. ],
       [  1. ,  60. ,  31.2, 135. , 160. ,  95. ],
       [  1. ,  55. ,  29.8, 128. , 150. ,  92. ],
       [  1. ,  32. ,  22.7, 110. , 105. ,  70. ],
       [  1. ,  42. ,  26.5, 118. , 135. ,  80. ],
       [  1. ,  48. ,  27.3, 125. , 145. ,  88. ],
       [  1. ,  35. ,  24.1, 113. , 120. ,  78. ],
       [  1. ,  58. ,  30.5, 132. , 158. ,  93. ],
       [  1. ,  41. ,  25.8, 121. , 138. ,  82. ],
       [  1. ,  47. ,  27. , 126. , 144. ,  87. ],
       [  1. ,  36. ,  24.9, 114. , 122. ,  76. ],
       [  1. ,  53. ,  29.1, 130. , 148. ,  89. ],
       [  1. ,  40. ,  26. , 119. , 132. ,  81. ],
       [  1. ,  61. ,  31.5, 136. , 162. ,  96. ],
       [  1. ,  39. ,  23.8, 117. , 128. ,  77. ],
       [  1. ,  49. ,  27.5, 129. , 146. ,  90. ],
       [  1. ,  37. ,  24.5, 116. , 124. ,  79. ],
       [  1. ,  54. ,  30. , 13

In [ ]:
Y

array([[1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1]])

In [ ]:
from numpy.linalg import inv
def weights(x,y):
   left = inv(x.T.dot(x))
   rgt = x.T.dot(y)
   return left.dot(rgt)

In [ ]:
W = weights(X, Y)
W.shape

(6, 1)

In [ ]:
W

array([[-3.6195539 ],
       [ 0.04538179],
       [-0.19649457],
       [ 0.01177053],
       [-0.01081425],
       [ 0.0876678 ]])

In [ ]:
def logistic(x, w):
    return 1/(1+np.exp(-x.dot(w)))

In [ ]:
ycap = logistic(X, W)
ycap.shape

(20, 1)

In [ ]:
ycap

array([[0.69030505],
       [0.70518259],
       [0.55637437],
       [0.76131559],
       [0.72528581],
       [0.41781363],
       [0.50544932],
       [0.69263919],
       [0.52591128],
       [0.73451843],
       [0.57252657],
       [0.68156439],
       [0.4518325 ],
       [0.68992813],
       [0.54020375],
       [0.77279287],
       [0.55406627],
       [0.73694948],
       [0.54875118],
       [0.70210433]])

In [ ]:
# np.where(condition, true value , false value)

ycap_labels = np.where(ycap>0.5, 1, 0)
ycap_labels

array([[1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1]])

In [ ]:
# compare originals and predicted.
np.c_[Y, ycap_labels]

array([[1, 1],
       [1, 1],
       [0, 1],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 1],
       [1, 1],
       [0, 1],
       [1, 1],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 1],
       [1, 1],
       [0, 1],
       [1, 1],
       [0, 1],
       [1, 1]])

In [ ]:
# find accuracy.

# number of predictions successful
pcnt = np.where(Y==ycap_labels)[0].size
n = Y.size
accuracy = pcnt/n * 100
print(" accuracy ",  accuracy)

 accuracy  65.0


In [ ]:
def accuracy(y, yc):
   pcnt = np.where(y==yc)[0].size
   n = y.size
   return pcnt/n * 100


In [ ]:
print("Accuracy ", accuracy(Y, ycap_labels))


Accuracy  65.0
