<a href="https://colab.research.google.com/github/venkatesh176/AI_Training/blob/main/nonlinear_lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
age = [20, 21, 24, 25, 26, 28, 30, 32, 35, 40, 42, 45, 48, 50 ]
len(age)

14

In [ ]:
h1 = age[:7]
print(h1)

[20, 21, 24, 25, 26, 28, 30]


In [ ]:
h2 = age[7:]
h2

[32, 35, 40, 42, 45, 48, 50]

In [ ]:
import numpy as np
H1 = np.array(h1)
income1 = 2* H1 + 50
income1

array([ 90,  92,  98, 100, 102, 106, 110])

In [ ]:
np.c_[H1, income1]

array([[20, 43],
       [21, 45],
       [24, 51],
       [25, 53],
       [26, 55],
       [28, 59],
       [30, 63]])

In [ ]:
H2 = np.array(h2)
income2 = 50 -   H2
np.c_[H2, income2]

array([[32, 18],
       [35, 15],
       [40, 10],
       [42,  8],
       [45,  5],
       [48,  2],
       [50,  0]])

In [ ]:
age

[20, 21, 24, 25, 26, 28, 30, 32, 35, 40, 42, 45, 48, 50]

In [ ]:
income = np.concatenate((income1, income2))
income

array([ 90,  92,  98, 100, 102, 106, 110,  18,  15,  10,   8,   5,   2,
         0])

In [ ]:
np.c_[age, income]

array([[ 20,  90],
       [ 21,  92],
       [ 24,  98],
       [ 25, 100],
       [ 26, 102],
       [ 28, 106],
       [ 30, 110],
       [ 32,  18],
       [ 35,  15],
       [ 40,  10],
       [ 42,   8],
       [ 45,   5],
       [ 48,   2],
       [ 50,   0]])

In [ ]:
# feature matrix.
# degree 1 . (linear regression)
ones = np.ones(len(age))
X1 = np.c_[ones, age]
X1.shape

(14, 2)

In [ ]:
Y = np.c_[income]

In [ ]:
from numpy.linalg import inv
def weights(x, y):
   return inv(x.T.dot(x)).dot(x.T.dot(y))

In [ ]:
W1 = weights(X1, Y)

In [ ]:
ycap1 = X1.dot(W1)
np.c_[Y, ycap1]

array([[ 90.        , 108.84308682],
       [ 92.        , 104.71511254],
       [ 98.        ,  92.33118971],
       [100.        ,  88.20321543],
       [102.        ,  84.07524116],
       [106.        ,  75.8192926 ],
       [110.        ,  67.56334405],
       [ 18.        ,  59.3073955 ],
       [ 15.        ,  46.92347267],
       [ 10.        ,  26.28360129],
       [  8.        ,  18.02765273],
       [  5.        ,   5.6437299 ],
       [  2.        ,  -6.74019293],
       [  0.        , -14.99614148]])

In [ ]:
def rscore(y, ycap):
   rss =  ((y-ycap)**2).sum()
   tss =  ((y-y.mean())**2).sum()
   return 1 - rss/tss


In [ ]:
rscore(Y, ycap1)

0.7614871075388379

In [ ]:
# experiment with non linear 2nd degree.
age = np.array(age)
age2 = age**2
X2 = np.c_[ones, age, age2]
X2.shape

(14, 3)

In [ ]:
W2 = weights(X2, Y)
W2

array([[ 2.28087596e+02],
       [-6.41414596e+00],
       [ 3.27574012e-02]])

In [ ]:
ycap2 = X2.dot(W2)
np.c_[Y , ycap2]

array([[ 90.        , 112.9076378 ],
       [ 92.        , 107.83654529],
       [ 98.        ,  93.01635657],
       [100.        ,  88.20732328],
       [102.        ,  83.46380478],
       [106.        ,  74.17331219],
       [110.        ,  65.14487881],
       [ 18.        ,  56.37850465],
       [ 15.        ,  43.72030441],
       [ 10.        ,  23.93360007],
       [  8.        ,  16.47752195],
       [  5.        ,   5.78476579],
       [  2.        ,  -4.31835715],
       [  0.        , -10.72619843]])

In [ ]:
rscore(Y, ycap2)

0.7643888429555852

In [ ]:
age3 = age**3
X3 = np.c_[ones, age, age2, age3]
W3 = weights(X3, Y)
W3

array([[-5.21317118e+02],
       [ 6.47863101e+01],
       [-2.11654640e+00],
       [ 2.06752580e-02]])

In [ ]:
ycap3 = X3.dot(W3)
rscore(Y, ycap3)

0.8461795949995257

In [ ]:
age4 = age**4
X4 = np.c_[ones, age, age2, age3, age4]
W4 = weights(X4, Y)
ycap4 = X4.dot(W4)
rscore(Y , ycap4)

0.8838541203827508

In [ ]:
age5 = age**5
X5 = np.c_[ones, age, age2, age3, age4, age5]
W5 = weights(X5, Y)
ycap5 = X5.dot(W5)
rscore(Y, ycap5)

0.8890582928574597

In [ ]:
age6 = age**6
X6 = np.c_[ones, age, age2, age3, age4, age5, age6]
W6 = weights(X6, Y)
ycap6 = X6.dot(W6)
rscore(Y, ycap6)

0.9230590808197886

In [ ]:
age7 = age**7
X7 = np.c_[ones, age, age2, age3, age4, age5, age6, age7]
W7 = weights(X7, Y)
ycap7 = X7.dot(W7)
rscore(Y, ycap7)

0.9230835901069528

In [ ]:
age8 = age**8
X8 = np.c_[ones, age, age2, age3, age4, age5, age6, age7, age8]
W8 = weights(X8, Y)
ycap8 = X8.dot(W8)
rscore(Y, ycap8)

0.9408042784038468

In [ ]:
age9 = age**9
X9 = np.c_[ones, age, age2, age3, age4, age5, age6, age7, age8, age9]
W9 = weights(X9, Y)
ycap9 = X9.dot(W9)
rscore(Y, ycap9)

0.9076942780036065

In [ ]:
# among all experiments , 8th degree model gave high accuracy.
# W8 is model fit.
print(W8)

[[-6.03977271e+05]
 [ 1.56651113e+05]
 [-1.74573181e+04]
 [ 1.09168060e+03]
 [-4.19005422e+01]
 [ 1.01109450e+00]
 [-1.49887834e-02]
 [ 1.24898040e-04]
 [-4.48277927e-07]]


In [ ]:
# new data.
new_age = [24, 35, 40, 21]
a = np.array(new_age)
a2 = a**2
a3 = a**3
a4 = a**4
a5 = a**5
a6 = a**6
a7 = a**7
a8 = a**8

In [ ]:
o = np.ones(len(new_age))
P = np.c_[o, a, a2, a3, a4, a5, a6, a7, a8]
P.shape

(4, 9)

In [ ]:
new_income = P.dot(W8)
new_income

array([[93.71208342],
       [ 1.41734618],
       [ 9.59493183],
       [93.02317124]])

In [ ]:
np.c_[new_age, new_income]

array([[24.        , 93.71208342],
       [35.        ,  1.41734618],
       [40.        ,  9.59493183],
       [21.        , 93.02317124]])

In [ ]:
np.c_[age, income]

array([[ 20,  90],
       [ 21,  92],
       [ 24,  98],
       [ 25, 100],
       [ 26, 102],
       [ 28, 106],
       [ 30, 110],
       [ 32,  18],
       [ 35,  15],
       [ 40,  10],
       [ 42,   8],
       [ 45,   5],
       [ 48,   2],
       [ 50,   0]])

In [ ]:
X8.shape

(14, 9)

9.757257895159535

In [ ]:
def scale(x):
   return (x-x.mean())/x.std()

X8_scale = np.copy(X8)


685.1857784720929

In [ ]:
for c in range(X8.shape[1]):
  if c!=0:
      X8_scale[:, c] = scale(X8_scale[:, c])


In [ ]:
for c in range(X8_scale.shape[1]):
  if c!=0:
     print(X8_scale[:, c].std())

0.9999999999999999
1.0
0.9999999999999999
1.0
0.9999999999999999
1.0
1.0
1.0


In [ ]:
Y_original= np.copy(Y)
Y = scale(Y)
Y

array([[ 0.77995404],
       [ 0.82328482],
       [ 0.95327716],
       [ 0.99660794],
       [ 1.03993872],
       [ 1.12660028],
       [ 1.21326184],
       [-0.77995404],
       [-0.84495021],
       [-0.95327716],
       [-0.99660794],
       [-1.06160411],
       [-1.12660028],
       [-1.16993106]])

In [ ]:
Y.std()

1.0000000000000002

In [ ]:
X = np.copy(X8_scale)
# W = random weights.
np.random.seed(101)
W = np.random.random((X8.shape[1], Y.shape[1]))*2 - 1
W.shape

(9, 1)

In [ ]:
conv = 0.0000001
flag=0
pe = 0
for i in range(100000):
   ycap = X.dot(W)
   ce = ((Y-ycap)**2).mean()
   if i%1000==0:
     print(" current error after " , i+1 , " iterations ", ce)
   delta = X.T.dot(Y-ycap)/Y.size
   W += delta * 0.002
   if np.abs(ce-pe) <=conv:
      print("Training Completed after ", i+1, " iterations ")
      flag=1
      break
   pe=ce
if flag==0:
   print("Training not completed  ")


 current error after  1  iterations  1.6713725195220799
 current error after  1001  iterations  0.1986136209534206
 current error after  2001  iterations  0.1977623056979792
 current error after  3001  iterations  0.19731255613735826
 current error after  4001  iterations  0.19700766159041033
 current error after  5001  iterations  0.19675899652321285
 current error after  6001  iterations  0.1965337894379958
 current error after  7001  iterations  0.196319846322849
 current error after  8001  iterations  0.19611259595616679
 current error after  9001  iterations  0.19591029237157104
 current error after  10001  iterations  0.1957122374252999
 current error after  11001  iterations  0.19551812224991474
 current error after  12001  iterations  0.19532778324608174
 current error after  13001  iterations  0.19514111165778525
 current error after  14001  iterations  0.19495802004940874
 current error after  15001  iterations  0.1947784298649362
 current error after  16001  iterations  0.19

In [ ]:
ycap_ml = X.dot(W)
rscore(Y, ycap_ml)

0.8093839132028385